### ISSUE TITLE
Download image to library / camera roll

### ISSUE THREAD

**Issue by ptkdev** [benjaminmwilson/cordova-plugin-downloader#1]
I try download png/jpg to camera roll but not work, image not appear in gallery
```
var dl = new download();

dl.Initialize({
    fileSystem : cordova.file.dataDirectory,
    folder: "code",
    unzip: false,
    remove: false,
    timeout: 0,
    success: DownloaderSuccess,
    error: DownloaderError
});


dl.Get("https://ptkdev.it/img/ptkdev_patryk_rzucidlo_avatar_1024.png");

function DownloaderError(err) {
    console.log("download error: " + err);
    alert("download error: " + err);
}

function DownloaderSuccess() {
    alert("Done!");
}
```

**Comment by benjaminmwilson** [comment]
Did it return any error code in err?

**Comment by ptkdev** [comment]
Nope, flow go to DownloaderSuccess() but in camera roll not exist folder and image. I use bad fileSystem? 

- Iphone 7 Plus
- iOS 11.2
- Cordova 8.0.0

**Comment by benjaminmwilson** [comment]
So I think it succeeded but is putting the file in cordova.file.dataDirectory/code/ptkdev_patryk_rzucidlo_avatar_1024.png where it won't be picked up by the gallery app as this is internal to your App.

I think you'll have to put it in cordova.file.externalRootDirectory instead of cordova.file.dataDirectory. As to what folder should be you can try "DCIM/Camera" instead of "code". I haven't tried this though. I designed it more to download files for the App's own use rather than saving to shared areas.

https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html has more details on the filesystem layout.

**Comment by ptkdev** [comment]
`externalRootDirectory` is for android, i test on iOS.
I try combination of various dataDirectory, syncedDataDirectory but nothing work. I try replace folder to DCIM/Camera but nothing.

Thanks anyway, I'll still be looking around.

**Comment by benjaminmwilson** [comment]
Ah sorry I thought you were on Android. I don't know but it's possible iOS requires special permissions to write to the Camera gallery. If you find a solution please do post it. Thanks

**Comment by ptkdev** [comment]
I found solution 1 minutes ago:
1) add permission to plist file /platforms/ios/[APP NAME]/*.plis
```
    <key>NSPhotoLibraryUsageDescription</key>
    <string>why app use permission</string>
```
2) install library `cordova plugin add https://github.com/CoSchedule/cordova-photo-library.git`

3) Add js code:
```
const options = {
      url: "https://ptkdev.it/img/ptkdev_patryk_rzucidlo_avatar_1024.png",
      albumName: "code",
  }
    
  cordova.plugins.PhotoLibrary.imageFromUrl(options, null, null);
```

I try solution with your plugin but fileSystem is only for "private" file, only app have access to this files. On android is possibile save to sdcard and gallery automatic detect this, on android nope.

Thanks <3
