### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by erikunha** [benjaminmwilson/cordova-plugin-downloader#3]
Hello there, i'm trying to use it but every file that i tried to download, get this CORS error:

`Access to XMLHttpRequest at 'https://conteudo.imguol.com.br/c/entretenimento/c4/2018/05/15/super-mario-odyssey-1526426783086_v2_1170x540.jpgx' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by benjaminmwilson-induction** [comment]
If you are on Android, wondering if you have the whitelist plugin at https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/ installed? And have `<access origin="*">` in `config.xml` as well as a Content Security Policy (CSP) set in your html. I've used this one with success:

```
<meta http-equiv="Content-Security-Policy" content="default-src * gap://ready; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' http://localhost:*">
```

If on iOS and using WkWebView (which I think is now the default due to UIWebView being depreciated) then you'll need the plugin https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix or https://github.com/oracle/cordova-plugin-wkwebview-file-xhr. Both plugins do the same thing I believe but I've only tried the first one. What happened is the WkWebView enforces CORS whereas the old UIWebView didn't.

The only other choice is to fix it server side by adding the HTTP Header `Access-Control-Allow-Origin: *` to the web server's responses.

**Comment by benjaminmwilson** [comment]
If you are on Android, wondering if you have the whitelist plugin at https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/ installed? And have `<access origin="*">` in `config.xml` as well as a Content Security Policy (CSP) set in your html. I've used this one with success:

```
<meta http-equiv="Content-Security-Policy" content="default-src * gap://ready; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' http://localhost:*">
```

If on iOS and using WkWebView (which I think is now the default due to UIWebView being depreciated) then you'll need the plugin https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix or https://github.com/oracle/cordova-plugin-wkwebview-file-xhr. Both plugins do the same thing I believe but I've only tried the first one. What happened is the WkWebView enforces CORS whereas the old UIWebView didn't.

The only other choice is to fix it server side by adding the HTTP Header `Access-Control-Allow-Origin: *` to the web server's responses.

**Comment by erikunha** [comment]
Ok, i'm trying on Android but still without success ang getting the following: 
`Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAHBAMAAADzDtBxAAAAD1BMVEUAAAAAAAAAAAAAAAAAAABPDueNAAAABXRSTlMUCS0gBIh/TXEAAAAaSURBVAjXYxCEAgY4UIICBmMogMsgFLtAAQCNSwXZKOdPxgAAAABJRU5ErkJggg==' because it violates the following Content Security Policy directive: "default-src * gap://ready". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by benjaminmwilson** [comment]
Seems like some progress. At least it is complaining about something different now.

Can also try:

```
<meta http-equiv="Content-Security-Policy" content="default-src * data: gap:; style-src 'self' 'unsafe-inline'; media-src *">
```
I added the `data` bit suggested by the whitelist plugin

...or:

```
<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'">
```
I got this one from https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/

When I wrote the plugin a used it for zip files and haven't tried images. Should still work but might take some trial and error with these sorts of security restrictions.

**Comment by erikunha** [comment]
Would be nice if i could use this plugin, i started to try with .dat files.. i'm sending what i'm getting:
![image](https://user-images.githubusercontent.com/27955793/50531716-085c2580-0af6-11e9-9e14-9e5530c6ead6.png)

**Comment by benjaminmwilson** [comment]
Hmm... in `config.xml` try:

```
<access origin="*" />
<allow-navigation href="*"/>
```

...and this CSP:

```
<meta http-equiv="Content-Security-Policy" content="default-src *; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; media-src *; img-src * data:;">
```

For this one, I added an explicit img-src.

**Comment by benjaminmwilson** [comment]
Hey just noticed from screen shot that this appears to be running just on browser at localhost (rather than from the actual App itself). You might find it works on a real device under Cordova since CORS is disabled  in Cordova (can still debug it by enabling USB debugging on device, plugging in via USB, and using Chrome dev tools as per https://developers.google.com/web/tools/chrome-devtools/remote-debugging/)

To get it working in your desktop browser, start your browser as discussed in https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

Good for debugging, but not much else.

**Comment by erikunha** [comment]
I was trying in my phone, real device but USB debugging on chrome. I think that might be some ionic config that is missing, any request that i tried got this CORS issue.

**Comment by benjaminmwilson** [comment]
Ah yeah could be. I did find some hints that seem like they would work for ionic at https://blog.ionicframework.com/handling-cors-issues-in-ionic/

But overall it will be much easier to run it inside the build ionic APK. CORS won't be an issue there on Android and also I very much suspect the cordova file libraries this plugin uses to actually write files to the filesystem won't work inside a browser only inside the APK.

**Comment by benjaminmwilson** [comment]
Please re-open if you'd like to chat further :-)
